package com.dentalclinic.exception;

public enum BookingErrorCode {
    VALIDATION_ERROR,
    INVALID_TIME_RANGE,
    BOOKING_IN_PAST,
    OUTSIDE_WORKING_HOURS,
    LUNCH_BREAK_CONFLICT,
    BOOKING_CONFLICT,
    SLOT_FULL,
    SLOT_NOT_FOUND,
    SERVICE_NOT_FOUND,
    SERVICE_INACTIVE,
    USER_NOT_ALLOWED,
    APPOINTMENT_NOT_FOUND,
    APPOINTMENT_STATUS_INVALID,
    CANCEL_WINDOW_CLOSED,
    RESCHEDULE_NOT_ALLOWED
}
