spring.application.name=SWP391_G5_Dental_Clinic
spring.thymeleaf.cache=false
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false



spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DentalClinic;encrypt=true;trustServerCertificate=true
spring.datasource.username=lam
spring.datasource.password=lamdz123
spring.datasource.driver-class-name =com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyendhlam11@gmail.com
spring.mail.password=awtw oymt qsib jiqp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

mail.enabled=true
mail.support.username=lenguyendaihai17@gmail.com
mail.support.password=hqdb leks cmjj esrh
mail.from=lenguyendaihai17@gmail.com
mail.from-name=GenZ Clinic

clinic.name=GenZ Clinic
clinic.address=
clinic.phone=
clinic.email=lenguyendaihai17@gmail.com

vnpay.tmnCode=2RN45RUR
vnpay.hashSecret=LA4W0MG4KAENLFOEFCKIUD8BIHQFFB9M
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/customer/payment/vnpay-return

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jackson.time-zone=Asia/Ho_Chi_Minh
server.port=8080

# Force UTF-8 response/request
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Thymeleaf UTF-8
spring.thymeleaf.encoding=UTF-8

# ===== AI Booking =====
ai.openai.api-key=YOUR_OPENAI_API_KEY
ai.openai.url=https://api.openai.com/v1/chat/completions
ai.openai.model=gpt-4o-mini
ai.booking.max-suggestions=5


customer.dev.default-user-id=3

payos.client-id=${PAYOS_CLIENT_ID:af579c0d-c45b-43fa-b9e5-dd39c79c9a45}
payos.api-key=${PAYOS_API_KEY:e5d5e07a-8a7e-4edd-9223-dcd1e31f4035}
payos.checksum-key=${PAYOS_CHECKSUM_KEY:119cddde5f5819e6f629d6723c5b15987763c8259e9c10e3e6045cf98948eb7f}
payos.base-url=${PAYOS_BASE_URL:https://api-merchant.payos.vn}
payos.return-url=${PAYOS_RETURN_URL:http://localhost:8080/public/payos/return}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:8080/public/payos/cancel}
